name: georgetheshihpoo
favicon: null
layout_spectrum: 0.28326305421069264
typography_spectrum: 0.12086363835260272
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9963979420717806
  lightness: 0.830752364359796
  saturation: 0.6878190240822732
  rhythmicContrast: 0.35587729630060494
purpose: []
